#!/bin/bash

if [ "$(whoami)" != 'root' ]; then
echo " Pleasae login as root user..."
exit 1;
fi
echo "Removing the Apaceh and reinstallation, Please wait a moments !"

sudo yum remove httpd -y >/dev/null 2>&1

echo -e "\e[40;38;5;82m Apache removed  \e[30;48;5;82m \e[0m "

echo -e "\e[40;38;5;82m Would you like me to install Apaceh Server (httpd) the Server  \e[30;48;5;82m [y/n]? \e[0m "
read q
if [[ "${q}" == "yes" ]] || [[ "${q}" == "y" ]]; then
sudo yum -y install httpd
sudo systemctl enable httpd.service
fi

echo -e "\e[40;38;5;82m Would you like me to Restart Apaceh Server (httpd) the Server  \e[30;48;5;82m [y/n]? \e[0m "

read q
if [[ "${q}" == "yes" ]] || [[ "${q}" == "y" ]]; then
sudo systemctl restart httpd.service
fi

echo "======================================"

echo -e "\e[1;31;42m Apache Installed Successfully and Running \e[0m"

sudo systemctl status httpd.service
echo "======================================"
