#!/bin/sh
#######################################
# Bash script to Install an Apache2, PHP 7.4, 8.1,Mariadb and PHPMyAdmin
# Written by Arvind Kumar Madhukar

# In case of any errors (e.g. MySQL) just re-run the script. Nothing will be re-installed except for the packages with errors.
#######################################
#Variables
root_password=P2^@lVG6f3O1
#######################################
# Update packages and Upgrade system
sudo apt-get update -y && sudo apt-get upgrade -y
## Install AMP Apache2, PHP 7.4, 8.1 and PHPMyAdmin
sudo apt install apache2 php-fpm -y
apt install apache2 libapache2-mod-fcgid -y
apt install software-properties-common -y
add-apt-repository ppa:ondrej/php
apt-get update -y
apt install php7.4 php7.4-fpm php7.4-common php7.4-intl php7.4-xsl php7.4-gd php7.4-mysql php7.4-pdo php7.4-curl php7.4-redis php7.4-zip php7.4-mbstring -y
sudo apt install php8.1 php8.1-fpm php8.1-common php8.1-mysql php8.1-xml php8.1-xmlrpc php8.1-curl php8.1-gd php8.1-imagick php8.1-cli php8.1-dev php8.1-imap php8.1-mbstring php8.1-opcache php8.1-soap php8.1-zip php8.1-redis php8.1-intl -y
sudo apt-get install libapache2-mod-php8.1 -y
sudo apt-get install libapache2-mod-php8.2 -y
sudo apt-get install libapache2-mod-php7.4 -y
sudo apt install mariadb-server -y
sudo systemctl enable mariadb
sudo systemctl start mariadb.service
sudo apt install phpmyadmin -y
sudo mysql -e  "ALTER USER 'root'@'localhost' IDENTIFIED BY '$root_password';"
sudo a2enmod rewrite
sudo mv /etc/apache2/ports.conf /etc/apache2/ports.conf.default
echo "Listen 8080" | sudo tee /etc/apache2/ports.conf
sed -i -e 's/80/8080/g' /etc/apache2/sites-available/000-default.conf
a2enmod actions fcgid alias proxy_fcgi
systemctl reload apache2 & systemctl restart apache2 & systemctl restart php7.4-fpm
echo "<h1 style='color: green;'>Apache2 8080</h1>" | sudo tee /var/www/html/index.html
echo "<?php phpinfo(); ?>" | sudo tee /var/www/html/info.php
a2enmod actions fcgid alias proxy_fcgi
systemctl reload apache2 & systemctl restart apache2 & systemctl restart php7.4-fpm & systemctl restart php8.1-fpm
a2enconf php7.4-fpm & a2disconf php8.1-fpm
systemctl reload apache2 & systemctl restart apache2 & systemctl restart php7.4-fpm & systemctl restart php8.1-fpm
sudo apt install nginx -y
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
root /var/www/html;

index index.html index.php index.htm index.nginx-debian.html;

server_name _;

location / {
try_files $uri @proxy;
}
location ~* \.(js|css|jpg|jpeg|gif|png|svg|ico|pdf|html|htm)$ {
expires 30d;
}
location @proxy {
proxy_pass http://127.0.0.1:8080;
include /etc/nginx/proxy_params;
}
location ~* \.php$ {
proxy_pass http://127.0.0.1:8080;
include /etc/nginx/proxy_params;
}
}" > /etc/nginx/sites-available/default
echo "<h1 style='color: green;'>nginx + apache2 </h1>" | sudo tee /var/www/html/index.html
sudo systemctl reload nginx
systemctl restart apache2
systemctl restart php7.4-fpm
systemctl restart php8.1-fpm
#######################################
